feat: alert and button
amirnathani9/NOMARK-UI-component-library pull request #2
Opened 2022-02-08 16:59 UTC by amirnathani9

## Change Logs
#Screenshots
![alert](https://user-images.githubusercontent.com/47810774/153036950-a37d0bba-8c98-4e35-bb05-7813cb2e9627.gif)

2022-02-08 17:44 UTC, Ashishgupta08 requested changes
Ui is really good.
Fix the navbar on the left

Make Components-based classes as well through which users can directly create components without providing utility classes and provide flexibility to the user through the `utility` classes.

2022-02-08 17:44 UTC, Ashishgupta08 commented on components/button/button.css
> +}
create a class `btn` and put styles of `utilities` classes

2022-02-08 17:44 UTC, Ashishgupta08 commented on components/alert/alert.html
> +        <div class="click-remove">
write better class names, `class` name should be SELF EXPLANATORY

2022-02-08 19:05 UTC, xii-vi approved these changes
_Work on the suggested comments. After that, you can merge._

2022-02-13 11:49 UTC, amirnathani9 commented on components/button/button.css
> +}
done with the changes

2022-02-13 11:50 UTC, merged